<template>
  <div class="loadingio-spinner-spinner-nkc25tqwcto"><div class="ldio-b02ul8pgrv">
    <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
    </div></div>
</template>

<script>
export default {

}
</script>
<style type="text/css">
@keyframes ldio-b02ul8pgrv {
  0% { opacity: 1 }
  100% { opacity: 0 }
}
.ldio-b02ul8pgrv div {
  left: 138.225px;
  top: 112.03500000000001px;
  position: absolute;
  animation: ldio-b02ul8pgrv linear 0.8695652173913042s infinite;
  background: #fca311;
  width: 14.55px;
  height: 14.55px;
  border-radius: 7.275px / 7.275px;
  transform-origin: 7.275px 33.465px;
}.ldio-b02ul8pgrv div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.7826086956521738s;
  background: #fca311;
}.ldio-b02ul8pgrv div:nth-child(2) {
  transform: rotate(36deg);
  animation-delay: -0.6956521739130433s;
  background: #fca311;
}.ldio-b02ul8pgrv div:nth-child(3) {
  transform: rotate(72deg);
  animation-delay: -0.608695652173913s;
  background: #fca311;
}.ldio-b02ul8pgrv div:nth-child(4) {
  transform: rotate(108deg);
  animation-delay: -0.5217391304347825s;
  background: #fca311;
}.ldio-b02ul8pgrv div:nth-child(5) {
  transform: rotate(144deg);
  animation-delay: -0.4347826086956521s;
  background: #fca311;
}.ldio-b02ul8pgrv div:nth-child(6) {
  transform: rotate(180deg);
  animation-delay: -0.3478260869565217s;
  background: #fca311;
}.ldio-b02ul8pgrv div:nth-child(7) {
  transform: rotate(216deg);
  animation-delay: -0.26086956521739124s;
  background: #fca311;
}.ldio-b02ul8pgrv div:nth-child(8) {
  transform: rotate(252deg);
  animation-delay: -0.17391304347826084s;
  background: #fca311;
}.ldio-b02ul8pgrv div:nth-child(9) {
  transform: rotate(288deg);
  animation-delay: -0.08695652173913042s;
  background: #fca311;
}.ldio-b02ul8pgrv div:nth-child(10) {
  transform: rotate(324deg);
  animation-delay: 0s;
  background: #fca311;
}
.loadingio-spinner-spinner-nkc25tqwcto {
    width: 291px;
    height: 291px;
    display: inline-block;
    overflow: hidden;
    background: rgba(NaN, NaN, NaN, 0);
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    position: absolute;
    margin: auto;
}
.ldio-b02ul8pgrv {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-b02ul8pgrv div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>